### ISSUE TITLE
代码没了。。。如何star

### ISSUE THREAD

**Issue by JiweiMaster** [gebiWangshushu/JDCaptchaCrack#3]

**Comment by matteao03** [comment]
同问

**Comment by JiweiMaster** [comment]
https://github.com/JiweiMaster/SlideVertifyCode
可以参考我后来破解顺丰快递查询滑块验证码的代码

**Comment by JiweiMaster** [comment]
> 同问
https://github.com/JiweiMaster/SlideVertifyCode
可以参考我后来破解顺丰快递查询滑块验证码的代码
